name: Cypress Test
on: [push]

jobs:
  cypress-run:
    environment: mqtt
    runs-on: ubuntu-latest
    env:
      PORT: 8080
      MONGODB_CONNECTION_STRING: mongodb://localhost:27017/
      MQTT_URL: ${{ secrets.MQTT_URL }}
      MQTT_USERNAME: ${{ secrets.MQTT_USERNAME }}
      MQTT_PASSWORD: ${{ secrets.MQTT_PASSWORD }}
    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['4.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Cypress
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run start:seed